name: Random Cron
on:
  workflow_run:
    workflows: ["刷步数"]
    types:
      - completed
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：README
      - name: random cron
        run: |
          source cron_convert.sh
          echo "configed CRON_HOURS ${{ vars.CRON_HOURS }}"
          persist_execute_log ${{ github.event_name }} ${{ vars.CRON_HOURS }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "random cron"
          git push origin master
